/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tasks */
        get: operations["GET_api_tasks"];
        put?: never;
        /** Create a task */
        post: operations["POST_api_tasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by ID */
        get: operations["GET_api_tasks_id"];
        /** Update a task */
        put: operations["PUT_api_tasks_id"];
        post?: never;
        /** Delete a task */
        delete: operations["DELETE_api_tasks_id"];
        options?: never;
        head?: never;
        /** Update a task */
        patch: operations["PATCH_api_tasks_id"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        d7b748f0194a5601d4c18199b51c1aed: {
            tasks?: {
                id: number;
                title: string;
                description?: string;
                done: boolean;
                created_at: string;
                updated_at: string;
            }[];
            meta?: {
                success?: boolean;
            };
        };
        "11cac7a528631363425253e40126403f": {
            title: string;
            description?: string;
            done?: boolean;
        };
        ce06eac03082560b848f48811a994fa2: {
            task?: {
                id: number;
                title: string;
                description?: string;
                done: boolean;
                created_at: string;
                updated_at: string;
            };
            meta?: {
                success?: boolean;
            };
        };
        "0a9bcbe16a06b1a4fc5faea646fa4a8f": {
            meta?: {
                success?: boolean;
                errors?: {
                    title?: string[];
                };
            };
        };
        "72f4773c6fe1f3543838bae1153a75ce": {
            meta?: {
                success?: boolean;
                error?: string;
            };
        };
        c05b3ceb32406df5ef17ddbd369eaef6: {
            status: number;
            error?: string;
        };
        "741e9e109aca798e3b547796273eebc5": {
            title?: string;
            description?: string;
            done?: boolean;
        };
        f4f91fa9e30496301c6f992a9102b1ae: {
            meta?: {
                success?: boolean;
            };
        };
    };
    responses: {
        /** @description Tasks */
        bb7d421ffcb3fe75e4727bfce51f5bf9: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["d7b748f0194a5601d4c18199b51c1aed"];
            };
        };
        /** @description Created */
        "48c8ad2bbd92443ef0c972d2c7d47273": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ce06eac03082560b848f48811a994fa2"];
            };
        };
        /** @description Validation error */
        df81bc72fcedd6c0018d35f41bcc3caa: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["0a9bcbe16a06b1a4fc5faea646fa4a8f"];
            };
        };
        /** @description Missing task param */
        "9ece6db49bc8f4b0bfe113ef4f05b4fa": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["72f4773c6fe1f3543838bae1153a75ce"];
            };
        };
        /** @description Task found */
        "8c5011d3bab8f49d3873a0db6638ced0": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ce06eac03082560b848f48811a994fa2"];
            };
        };
        /** @description Not found */
        "46ac2f9c36cf1a3281a7bb623be16249": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["72f4773c6fe1f3543838bae1153a75ce"];
            };
        };
        /** @description Updated */
        f8d073d2a50a96227321f14aadbd1efd: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ce06eac03082560b848f48811a994fa2"];
            };
        };
        /** @description Deleted */
        "720d4914627c5848af85b036552e235a": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["f4f91fa9e30496301c6f992a9102b1ae"];
            };
        };
    };
    parameters: {
        /** @description The task ID */
        f2d93b2709f8aedff2c02092238c3a8e: number;
    };
    requestBodies: {
        /** @description Task attributes */
        "05d1d58791d3ce51b0342ab5c9df5125": {
            content: {
                "application/json": components["schemas"]["11cac7a528631363425253e40126403f"];
            };
        };
        /** @description Task attributes */
        "5fde5fb70b584720d331d6e83e523641": {
            content: {
                "application/json": components["schemas"]["741e9e109aca798e3b547796273eebc5"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GET_api_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["bb7d421ffcb3fe75e4727bfce51f5bf9"];
        };
    };
    POST_api_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["05d1d58791d3ce51b0342ab5c9df5125"];
        responses: {
            201: components["responses"]["48c8ad2bbd92443ef0c972d2c7d47273"];
            400: components["responses"]["9ece6db49bc8f4b0bfe113ef4f05b4fa"];
            422: components["responses"]["df81bc72fcedd6c0018d35f41bcc3caa"];
        };
    };
    GET_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task ID */
                id: components["parameters"]["f2d93b2709f8aedff2c02092238c3a8e"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["8c5011d3bab8f49d3873a0db6638ced0"];
            404: components["responses"]["46ac2f9c36cf1a3281a7bb623be16249"];
        };
    };
    PUT_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task ID */
                id: components["parameters"]["f2d93b2709f8aedff2c02092238c3a8e"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["5fde5fb70b584720d331d6e83e523641"];
        responses: {
            200: components["responses"]["f8d073d2a50a96227321f14aadbd1efd"];
            404: components["responses"]["46ac2f9c36cf1a3281a7bb623be16249"];
            422: components["responses"]["df81bc72fcedd6c0018d35f41bcc3caa"];
        };
    };
    DELETE_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task ID */
                id: components["parameters"]["f2d93b2709f8aedff2c02092238c3a8e"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["720d4914627c5848af85b036552e235a"];
            404: components["responses"]["46ac2f9c36cf1a3281a7bb623be16249"];
        };
    };
    PATCH_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task ID */
                id: components["parameters"]["f2d93b2709f8aedff2c02092238c3a8e"];
            };
            cookie?: never;
        };
        requestBody?: components["requestBodies"]["5fde5fb70b584720d331d6e83e523641"];
        responses: {
            200: components["responses"]["f8d073d2a50a96227321f14aadbd1efd"];
            404: components["responses"]["46ac2f9c36cf1a3281a7bb623be16249"];
            422: components["responses"]["df81bc72fcedd6c0018d35f41bcc3caa"];
        };
    };
}
